name: Update

on:
  schedule:
    - cron: "0/15 * * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./tools/version-checker

    steps:
      - uses: actions/checkout@v2
      - name: Install node v18
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install
      - name: Run Updater
        run: ./update-version
      - name: Store WA Version
        run: echo WA_VERSION=`cat ./.version` >> $GITHUB_ENV
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: auto-wa-web-update/patch
          delete-branch: true
          commit-message: Atualizado vers達o suportada do WhatsApp Web para v${{ env.WA_VERSION }}
          title: Vers達o do WhatsApp Web atualizada (${{ env.WA_VERSION }})
          body: |
            Uma nova vers達o do WhatsApp Web foi detectada! 
            
            Os testes devem ser executados nesta nova vers達o antes do merge.
          labels: WhatsApp Atualizado
          reviewers: yurih567,mazinsw,Fernandoborgesjr
